### ISSUE TITLE
Don't hard code malloc/free invocations

### ISSUE THREAD

**Issue by nemequ** [mbitsnbites/liblzg#2]
I'd like to be able to use a custom function to allocate and free memory instead of having liblzg just call malloc/free.

AFAICT the decoder doesn't use malloc/free.  For the encoder the amount of memory required is determined by the level + fast flag.  I think it would be easier to have the caller pass a buffer instead of callbacks for allocating and freeing, and that would also allow a buffer to be reused across multiple operations.  What do you think of something like this?

``` C
size_t LZG_WorkMemSize (lzg_encoder_config *config);

lzg_uint32_t LZG_Encode(const unsigned char *in, lzg_uint32_t insize,
                        unsigned char *out, lzg_uint32_t outsize,
                        lzg_encoder_config_t *config,
                        void* workmem);
```

Or, if you want to preserve the existing API, `LZG_Encode` could call a `LZG_EncodeFull` (or whatever) which would have a workmem argument.

On a related note, in `_LZG_DetermineMarkers`, it seems to me that `hist` is small enough that it could be placed on the stack.

**Comment by mbitsnbites** [comment]
@nemequ This sounds like a fine suggestion (a new method in addition to the existing one). If you provide a suggested solution via a pull request, we might get a fix in quickly.

Happy new 2016!

**Comment by nemequ** [comment]
Done.

Got the PR in _just_ before 2016 GMT.  Happy 2016 to you, too :)
